name: Deploy to GitHub Pages

# Disabled to avoid conflicts with Vercel deployment
# on:
#   push:
#     branches: [ main ]
#     paths-ignore:
#       - 'dist/**'
#       - 'assets/**'
#       - '*.html'
#       - '*.png'
#       - '*.jpg'
#       - '*.ico'
#       - '*.svg'
#       - 'robots.txt'
#   workflow_dispatch:

on:
  workflow_dispatch: # Only manual triggers allowed

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Deploy to main branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Remove existing built files
        git rm -rf dist/ assets/ *.html *.png *.jpg *.ico *.svg robots.txt 2>/dev/null || true
        
        # Copy new built files to root
        cp -r dist/* .
        
        # Add all files
        git add .
        
        # Commit and push
        git commit -m "Deploy to main branch [skip ci]" || exit 0
        git push origin main 